== *RFQ FIX messages*

* https://www.onixs.biz/fix-dictionary/4.4/msgType_AH_6572.html[RFQ Request <AH>]
====
* https://www.onixs.biz/fix-dictionary/4.4/msgType_R_82.html[*Quote Request <R>*]
* https://www.onixs.biz/fix-dictionary/4.4/msgType_AG_6571.html[*Quote Request Reject <AG>*]
* https://www.onixs.biz/fix-dictionary/4.4/msgType_S_83.html[*Quote <S>*]
* https://www.onixs.biz/fix-dictionary/4.4/msgType_AJ_6574.html[*Quote Response <AJ>*]
====
* https://www.onixs.biz/fix-dictionary/4.4/msgType_AI_6573.html[Quote Status Report <AI>]
* https://www.onixs.biz/fix-dictionary/4.4/msgType_a_97.html[Quote Status Request <a>]
* https://www.onixs.biz/fix-dictionary/4.4/msgType_Z_90.html[Quote Cancel <Z>]

*Eurex* exchange uses only the selected above 4 messages (_chapter 3.1 Request for Quote (RFQ), page 6 in https://www.eurexchange.com/resource/blob/196150/c89bf1d358ef0669d3320208be133bfd/data/eb_16_054_e_Attach-2.pdf[Eurex FIX tests spec]_):

[width="95%",cols=".^8%, .^12%, .^80%", options="header"]
|=================================
| Message | Issuer | Usage

|https://www.onixs.biz/fix-dictionary/4.4/msgType_R_82.html[*Quote Request <R>*]
|Initiator
|to initiate RFQ

|https://www.onixs.biz/fix-dictionary/4.4/msgType_AG_6571.html[*Quote Request Reject <AG>*]
|Initiator or Dealer
|to reject/time-out RFQ:

- Initiator sends it in case of time-out (RFQ expiry).

- Dealer sends it to reject RFQ.

|https://www.onixs.biz/fix-dictionary/4.4/msgType_S_83.html[*Quote <S>*]
|Dealer
|to quote the proposed RFQ

|https://www.onixs.biz/fix-dictionary/4.4/msgType_AJ_6574.html[*Quote Response <AJ>*]
|Initiator
|to cancel RFQ

|=================================

=== *RFQ Request <AH>*

FIX Standard specification: https://www.onixs.biz/fix-dictionary/4.4/msgType_AH_6572.html[RFQ Request <AH>]

====
*Used by liquidity providers to indicate to the market for which instruments they are interested in receiving Quote Requests*.
====

It can be used to register interest in receiving quote requests for a single instrument or for multiple instruments.

=== *Quote Request <R>*

FIX Standard specification: https://www.onixs.biz/fix-dictionary/4.4/msgType_R_82.html[Quote Request <R>]

====
Used *to request quotes from brokers _prior to placement of an order_*. It is commonly referred to as an _Request For Quote (RFQ)_.

In the tradeable and restricted tradeable quote models the *Quote Request <R>* may be preceded by the https://www.onixs.biz/fix-dictionary/4.4/msgType_AH_6572.html[RFQ Request <AH>] message.
====

The *Quote Request <R>* message can be used to request quotes on single products or multiple products.

* Securities quotes can be requested as either *market quotes (indicative quotes)* or *quotes for a specific quantity and side*. If https://www.onixs.biz/fix-dictionary/4.4/tagNum_38.html[OrderQty <38>] and https://www.onixs.biz/fix-dictionary/4.4/tagNum_54.html[Side <54>] are absent, a market-style quote (bid x offer, size x size) will be returned.

* For tradeable quote requests it is possible to specify *the time period* in which *the request is valid for* and the time period which *the resulting quote must be valid for*.

=== *Quote Request Reject <AG>*

FIX Standard specification: https://www.onixs.biz/fix-dictionary/4.4/msgType_AG_6571.html[Quote Request Reject <AG>]

====
Used to reject https://www.onixs.biz/fix-dictionary/4.4/msgType_R_82.html[Quote Request <R>] messages for all quoting models by quote ID using mandatory https://www.onixs.biz/fix-dictionary/4.4/tagNum_131.html[QuoteReqID] field.

Reason of rejection is stated in the field https://www.onixs.biz/fix-dictionary/4.4/tagNum_658.html[ QuoteRequestRejectReason <658>]:

* 1 = Unknown symbol (Security)
* 2 = Exchange(Security) closed
* 3 = Quote Request <R> exceeds limit
* 4 = Too late to enter
* 5 = Invalid price
* 6 = Not authorized to request quote
* 7 = No match for inquiry
* 8 = No market for instrument
* 9 = No inventory
* 10 = Pass
* 99 = Other
====

=== *Quote <S>*

FIX Standard specification: https://www.onixs.biz/fix-dictionary/4.4/msgType_S_83.html[Quote <S>]

====
Used as the response to a https://www.onixs.biz/fix-dictionary/4.4/msgType_R_82.html[Quote Request <R>] or a https://www.onixs.biz/fix-dictionary/4.4/msgType_AJ_6574.html[Quote Response <AJ>] message in both indicative, tradeable, and restricted tradeable quoting markets.

In tradeable and restricted tradeable quoting models, the market maker sends quotes into a market as opposed to sending quotes directly to a counterparty.

The type of quote is identified by its field https://www.onixs.biz/fix-dictionary/4.4/tagNum_537.html[QuoteType <537>]:

* 0 = Indicative
* 1 = Tradeable
* 2 = Restricted Tradeable
* 3 = Counter (tradable)

====

=== *Quote Response <AJ>*

FIX Standard specification: https://www.onixs.biz/fix-dictionary/4.4/msgType_AJ_6574.html[Quote Response <AJ>]

====
This message is used to respond to https://www.onixs.biz/fix-dictionary/4.4/msgType_S_83.html[Quote <S>] message.

It is also used to counter a https://www.onixs.biz/fix-dictionary/4.4/msgType_S_83.html[Quote <S>] or end a negotiation dialog.

Type of this response is indentified by its mandatory field https://www.onixs.biz/fix-dictionary/4.4/tagNum_694.html[QuoteRespType <694>]:

* 1 = Hit/Lift
* 2 = Counter
* 3 = Expired
* 4 = Cover
* 5 = Done Away
* 6 = Pass

====

=== *Quote Status Report <AI>*

FIX Standard specification: https://www.onixs.biz/fix-dictionary/4.4/msgType_AI_6573.html[Quote Status Report <AI>]


=== *Quote Status Request <a>*

FIX Standard specification: https://www.onixs.biz/fix-dictionary/4.4/msgType_a_97.html[Quote Status Request <a>]


=== *Quote Cancel <Z>*

FIX Standard specification: https://www.onixs.biz/fix-dictionary/4.4/msgType_Z_90.html[Quote Cancel <Z>]

====
Used by an originator of quotes to cancel quotes.
====

The Quote Cancel message supports cancelation of:

* All quotes
* Quotes for a specific symbol or security ID
* All quotes for a security type
* All quotes for an underlying


Canceling a https://www.onixs.biz/fix-dictionary/4.4/msgType_S_83.html[Quote <S>] is accomplished by indicating the type of cancelation in the https://www.onixs.biz/fix-dictionary/4.4/tagNum_298.html[QuoteCancelType <298>] field.

It is recommended that all Cancel messages be acknowledged using the https://www.onixs.biz/fix-dictionary/4.4/msgType_AI_6573.html[Quote Status Report <AI>] message.

====
The Quote Cancelation only applies to quotes made by the current FIX user.
====

====
Options usage notes:

Normal usage would be to cancel the quotes for a symbol. This is the reason that the use of further nesting similar to the quote is not used in this message. You are able to cancel quotes for specific series by specifying each option series in the repeating group.
====


//
