== *Introduction*

Institutions can use the `FIX Drop Copy` feed to receive confirmations of orders and corresponding updates on the PowerTrade exchange.

PowerTrade will report all orders and corresponding updates on the exchange using:

====
* <<FIX_Execution_Report,Execution Report <8> >>
//* Trade Capture Report <AE>.
====


Listed above updates can occur via orders placed using:
====
* a https://htmlpreview.github.io/?https://github.com/Power-Trade/fix-api-clients/blob/develop/docs/OrderEntry.html[FIX API] session;
//* a https://docs.api.power.trade/[REST API] session;
* a https://docs.api.power.trade/[WebSocket API] session;
* user logged in to the PowerTrade mobile application (https://apps.apple.com/app/apple-store/id1548085709?pt=122484983&ct=Home%20Page&mt=8[iOS], https://play.google.com/store/apps/details?id=com.pt.powertrade&referrer=utm_source%3DHome%2520Page[Android]);
* user logged in to the PowerTrade https://app.power.trade/[web application];
====
====
`FIX Drop Copy` reports on orders from *_all_* of these sources and from *_all_* sub-accounts.
//, distinguished by the value supplied in the PartyID <448> field.
====

====
Please note that *Read-Only* API key `is required` as a password in <<FIX_Logon, Logon <A> >> of `FIX Drop Copy` sessions.

API keys can be generated in https://app.power.trade/api-keys[PowerTrade Web App].
====

There are no client-originated messages supported on this channel except for the session-management ones.

// include::../FIX/survey.asciidoc[]
